version: "3.1"

services:
  db:
    image: mysql:8.0
    container_name: db
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    volumes:
      - dbdata:/var/lib/mysql
    command: "--default-authentication-plugin=mysql_native_password"
    ports: 
      - 3306:3306
    networks:
      - wpnet

  wordpress:
    depends_on:
      - db
    image: wordpress:php7.4-fpm-alpine
    container_name: wordpress
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    volumes:
      - ./data/wordpress:/var/www/html
      - ./config/php/docker-php-ext-upload.ini:/usr/local/etc/php/conf.d/docker-php-ext-upload.ini
    networks:
      - wpnet

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./data/wordpress:/var/www/html
      - ./config/nginx:/etc/nginx/conf.d
    networks:
      - wpnet
volumes:
  wordpress:
  dbdata:

networks:
  wpnet:
    driver: bridge
